#!bin/bash
cat vars.tf
cat  provider.tf
cat terraform.tfvars
cat instance.tf




# terraform --version

# terraform init

# terraform apply -yes

# terraform destroy

# terraform plan

# terraform plan -out out.terraform

# terraform apply out.terraform


# ls ~/aws/credentials